In [1]:
import pandas as pd
import numpy as np

In [4]:
def clean_and_engineer(df):
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
    
    # Drop rows missing critical info
    df.dropna(subset=['model', 'year', 'price_usd', 'mileage_km'], inplace=True)
    
    # Feature: price per km
    df['price_per_km'] = df['price_usd'] / df['mileage_km'].replace(0, np.nan)
    
    # Feature: vehicle age
    current_year = pd.Timestamp.now().year
    df['vehicle_age'] = current_year - df['year']
    
    # Feature: engine category
    df['engine_category'] = pd.cut(df['engine_size_l'], bins=[0, 2.0, 3.0, 5.0],
                                   labels=['small', 'medium', 'large'])
    
    # Feature: is automatic
    df['is_automatic'] = df['transmission'].str.lower().str.contains('auto').astype(int)
    
    # Feature: sales intensity
    df['sales_intensity'] = pd.cut(df['sales_volume'],
                                   bins=[0, 100, 500, 1000, np.inf],
                                   labels=['low', 'medium', 'high', 'very high'])
    
    return df

In [7]:
# Replace Path
file_path = "C:/Users/eguen/OneDrive/Desktop/bmw_sales.csv"
df_raw = pd.read_csv(file_path)

In [9]:
df = clean_and_engineer(df_raw)
df.head()

,model,year,region,color,fuel_type,transmission,engine_size_l,mileage_km,price_usd,sales_volume,sales_classification,price_per_km,vehicle_age,engine_category,is_automatic,sales_intensity
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High,0.650684,9,large,0,very high
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low,0.651092,12,small,1,very high
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low,10.305250,3,large,1,very high
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low,2.237057,1,small,1,very high
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low,0.408561,5,medium,0,very high